AWSTemplateFormatVersion: "2010-09-09"
Description: "sosw_worker_assistant"

Parameters:
  ExecutionPolicy:
    Description: "Managed execution policy for sosw lambdas."
    Type: String
    Default: 'AWSLambdaBasicExecutionRole'

  ConfigTableName:
    Description: "Config Table."
    Type: String
    Default: 'config'

Resources:

  LambdaSoswWorkerAssistantRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - "lambda.amazonaws.com"
          Action:
          - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - !Sub "arn:aws:iam::aws:policy/service-role/${ExecutionPolicy}"

      Policies:
      - PolicyName: "SoswWorkerAssistantPermissions"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:

          - Effect: "Allow"
            Action:
              - "dynamodb:UpdateItem"
              - "dynamodb:DescribeTable"
            Resource:
#              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}/table/${Fn::ImportValue: 'sosw-ddb-tasks'}/*"
              - Fn::Join:
                - ':'
                - - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}"
                  - Fn::Join:
                    - '/'
                    - - "table"
                      - Fn::ImportValue: "sosw-ddb-tasks"
                      - "*"
              - Fn::Join:
                - ':'
                - - "arn:aws:dynamodb"
                  - !Ref AWS::Region
                  - !Ref AWS::AccountId
                  - Fn::Join:
                    - '/'
                    - - "table"
                      - Fn::ImportValue: "sosw-ddb-tasks"

# You can provide access explicitly here, but we normally recommend keeping it in the Custom policy of ConfigTable.
# See examples/yaml/sosw-shared-dynamodb.yaml
          - Effect: "Allow"
            Action:
              - "dynamodb:Query"
              - "dynamodb:DescribeTable"
            Resource:
              - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ConfigTableName}"

      RoleName: "lambda_sosw_worker_assistant"


#################################
# Lambda Function for Essential #
#################################
  LambdaSoswWorkerAssistant:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Sub "sosw-s3-${AWS::AccountId}"
        S3Key: "sosw/packages/sosw_worker_assistant.zip"
      Description: "ABS. CloudFormation managed sosw WorkerAssistant."
      FunctionName: "sosw_worker_assistant"
      Handler: "app.lambda_handler"
      MemorySize: 256
      Role: !GetAtt LambdaSoswWorkerAssistantRole.Arn
      Runtime: "python3.7"
      Timeout: 30

      Tags:
       -
         Key: 'Environment'
         Value: 'dev'


##############################################
# Permissions for CloudWatch ScheduledEvents #
# The actual Rules are configured in the     #
# scheduled-rules.yaml template.             #
##############################################
  PermissionForEventsToInvokeLambdaSoswWorkerAssistant:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName:
        Ref: "LambdaSoswWorkerAssistant"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"


#############################################
# Export Values to CloudFormation Namespace #
#############################################
Outputs:

  LambdaSoswWorkerAssistant:
    Description: "Sosw WorkerAssistant Essential"
    Value: !GetAtt LambdaSoswWorkerAssistant.Arn
    Export:
      Name: "sosw-lambda-worker-assistant"
