AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sosw_tutorial_pull_tweeter_hashtags

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  TpthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: sosw_tutorial_pull_tweeter_hashtags/
      Handler: app.lambda_handler
      Runtime: python3.7
      FunctionName: sosw_tutorial_pull_tweeter_hashtags

Outputs:
  TpthFunction:
    Description: "sosw_tutorial_pull_tweeter_hashtags Lambda Function ARN"
    Value: !GetAtt TpthFunction.Arn
  TpthFunctionIamRole:
    Description: "Implicit IAM Role created for sosw_tutorial_pull_tweeter_hashtags function"
    Value: !GetAtt TpthFunctionRole.Arn
